class_name HouseData
extends Resource

## One house *model* (e.g. the Highlands trano gasy): its baked art, where its
## walls, porch and door are, and the interior all houses of this model
## share. Every house placed in any village is a House scene pointing at one
## of these - a village's look is a handful of HouseData, not hand-built
## scenes.
##
## GENERATED by tools/bake_house.gd from tools/house_models/<id>.json - edit
## the JSON (measured on the master art) and re-bake, never this .tres: the
## next bake overwrites it.
##
## Every rect is in body_texture pixels, top-left origin. The texture's
## bottom-left corner is the House node's position (on the 48 px grid).

@export var id: String = ""
@export var display_name: String = ""

@export_group("Art")
## The whole building at its in-game size (baked, never scaled at runtime).
@export var body_texture: Texture2D
## Drawn over the door while the player stands at it.
@export var door_open_texture: Texture2D
@export var door_open_position: Vector2 = Vector2.ZERO

@export_group("Layout")
## The building's base on the ground: solid, the player walks around it.
@export var footprint: Rect2 = Rect2()
## Walkable recess cut out of the footprint's front edge (porch, veranda) -
## leave empty for a door flush with the wall.
@export var entrance: Rect2 = Rect2()
## The doorway. Its bottom edge is the threshold: stepping on it goes inside,
## and it's the house's depth line - the player is drawn in front of the
## house below it, behind it above it.
@export var door: Rect2 = Rect2()

@export_group("Interior")
## The interior every house of this model opens onto (a zone id), shared -
## empty: houses of this model are decorative unless a placed House names
## its own interior.
@export var interior_zone: String = ""
## Entry marker in that interior.
@export var interior_spawn: String = ""

@export_group("Feel")
## House opacity while the player walks behind it, so they're never lost.
@export_range(0.0, 1.0, 0.05) var behind_alpha: float = 0.45
